unique_ids:
  assets:
    standard-page.html: W6T32EGLQM4I5QGG2WFT2G5QSZRYRDWJ
    theme.css: QP3YNSNHDIKEWORPO5H37MHQL6BBTNKG
  forms:
    Form1: 6QCWYXXW7ZSLKA2ZML3RVH74NYYD6VUZ
    Form1.RowTemplate1: '1732391935652823503199916.7084'
    Form1.RowTemplate2: '1732391941611103764664727.90979'
  modules: {}
  scripts: {}
  server_modules: {}
