unique_ids:
  assets:
    standard-page.html: W6T32EGLQM4I5QGG2WFT2G5QSZRYRDWJ
    theme.css: QP3YNSNHDIKEWORPO5H37MHQL6BBTNKG
  forms:
    Form1: 6QCWYXXW7ZSLKA2ZML3RVH74NYYD6VUZ
  modules: {}
  scripts: {}
  server_modules: {}
